name: Download and Upload Files from Issue

on:
  issues:
    types: [opened]

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: clone environment
      run: |
        git clone https://github.com/404-novel-project/font_tables_lib

    - name: Extract download link from issue
      id: extract-link
      run: |
        ISSUE_BODY="${{ github.event.issue.body }}"
        DOWNLOAD_LINK=$(echo "$ISSUE_BODY" | grep -oP '(?<=http://|https://)[^ ]+')
        echo "::set-output name=download_link::https://$DOWNLOAD_LINK"

    - name: Download font
      id: download-file
      run: |
        cd font_tables_lib
        mkdir sample_font 
        cd sample_font
        DOWNLOAD_LINK="${{ steps.extract-link.outputs.download_link }}"
        wget "$DOWNLOAD_LINK"
        FILENAME=$(basename "$DOWNLOAD_LINK")

    - name: process font
      run: |
        cd font_tables_lib
        python main.py
        mv gen/* ../
        cd ../
        rm -rf font_tables_lib
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add downloaded_file
        git commit -m "Add downloaded file from issue #${{ github.event.issue.number }}"
        git push
    
    - name: Comment and close the issue
      run: |
        ISSUE_NUMBER="${{ github.event.issue.number }}"
        COMMENT_BODY="文件已处理完成"
        gh issue comment $ISSUE_NUMBER --body "$COMMENT_BODY"
        gh issue close $ISSUE_NUMBER
